openapi: 3.0.0
info:
  title: Swagger Petstore
  version: 1.0.0
paths:
  /pet/findByStatus:
    get:
      summary: Finds Pets by status
      operationId: findPetsByStatus
      parameters:
        - name: status
          in: query
          description: Status values that need to be considered for filter
          required: true
          schema:
            type: array
            items:
              type: string
              enum:
                - available
                - pending
                - sold
            collectionFormat: multi
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        status:
          type: string
          enum:
            - available
            - pending
            - sold